# Generated by Django 6.0.3 on 2026-04-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user_1', 'User 1'), ('user_2', 'User 2'), ('admin', 'Admin')], default='user_1', max_length=20),
        ),
    ]
