# Generated by Codex on 2026-04-29

from django.db import migrations, models


def migrate_legacy_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')

    role_map = {
        'user_1': 'manager',
        'user_2': 'production_assistant',
    }

    for legacy_role, next_role in role_map.items():
        User.objects.filter(role=legacy_role).update(role=next_role)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('accountant', 'Accountant'),
                    ('production_assistant', 'Production Assistant'),
                    ('estimator', 'Estimator'),
                    ('qs', 'QS'),
                    ('manager', 'Manager'),
                    ('admin', 'Admin'),
                ],
                default='accountant',
                max_length=20,
            ),
        ),
    ]
