# Generated by Django 6.0.3 on 2026-04-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('is_public_holiday', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('total_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('regular_duty_hours', models.DecimalField(decimal_places=2, default=9, max_digits=6)),
                ('normal_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sunday_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('public_holiday_ot', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('medical_leave_with_doc', models.BooleanField(default=False)),
                ('medical_leave_without_doc', models.BooleanField(default=False)),
                ('absent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__employee_id'],
            },
        ),
    ]
