# Generated by Django 6.0.3 on 2026-04-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_annualleave_salaryadvance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_month', models.PositiveSmallIntegerField()),
                ('deduction_year', models.PositiveIntegerField()),
                ('deduction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_deductions', to='employees.employee')),
            ],
            options={
                'ordering': ['-deduction_date', 'employee__employee_id'],
                'unique_together': {('employee', 'deduction_month', 'deduction_year')},
            },
        ),
    ]
