# Generated by Django 6.0.3 on 2026-04-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_salaryadvancededuction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('cost_code', models.CharField(choices=[('Material', 'Material'), ('Machining', 'Machining'), ('Coating', 'Coating'), ('Consumables', 'Consumables'), ('Subcontracts', 'Subcontracts'), ('Labour', 'Labour'), ('Freight&Customs', 'Freight&Customs'), ('Prelims', 'Prelims'), ('FOH', 'FOH'), ('Commitments', 'Commitments'), ('Contingency', 'Contingency')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='AssociatedCostPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recovery_advance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retention', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('release_retention', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='employees.associatedcostentry')),
            ],
            options={
                'ordering': ['entry__serial_number'],
            },
        ),
        migrations.CreateModel(
            name='AssociatedCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_cost_items', to='employees.employee')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees.associatedcostentry')),
            ],
            options={
                'ordering': ['entry', 'line_number'],
                'unique_together': {('entry', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='AssociatedCostPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_quantity', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_cost_payment_items', to='employees.employee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='employees.associatedcostpayment')),
            ],
            options={
                'ordering': ['payment', 'line_number'],
                'unique_together': {('payment', 'line_number')},
            },
        ),
    ]
