# Generated by Django 6.0.3 on 2026-04-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_associatedcostentry_associatedcostpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('payroll_date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('Staff', 'Staff'), ('Labour', 'Labour')], max_length=20)),
                ('calendar_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('medical_leave_with_doc_days', models.PositiveIntegerField(default=0)),
                ('medical_leave_without_doc_days', models.PositiveIntegerField(default=0)),
                ('annual_leave_days', models.PositiveIntegerField(default=0)),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('normal_ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sunday_ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('public_holiday_ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('basic_salary_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('basic_salary_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('normal_ot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sunday_ot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('public_holiday_ot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ot_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('leave_salary_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employees.employee')),
            ],
            options={
                'ordering': ['payroll_date', 'employee__employee_id'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
