# Generated by Django 6.0.3 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_payrollrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedcostpaymentitem',
            name='gl_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
