# Generated by Django 6.0.3 on 2026-04-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=50)),
                ('company_telephone', models.CharField(blank=True, default='', max_length=50)),
                ('product_details', models.TextField(blank=True, default='')),
                ('review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('cost_code', models.CharField(choices=[('MAT', 'MAT'), ('CON', 'CON'), ('LAB', 'LAB'), ('FOH', 'FOH'), ('SHP', 'SHP'), ('CUS', 'CUS')], max_length=10)),
                ('po_date_original', models.DateField()),
                ('po_date_revised', models.DateField(blank=True, null=True)),
                ('po_rev_number', models.CharField(blank=True, default='', max_length=100)),
                ('item_description', models.TextField()),
                ('currency', models.CharField(max_length=50)),
                ('po_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('po_amount_aed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_aed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po_amount_inc_vat_aed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_of_payment', models.CharField(choices=[('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Card', 'Card')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-po_date_original', 'po_number'],
            },
        ),
    ]
