# Generated by Django 6.0.3 on 2026-04-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('retention', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_entry', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['purchase_order__po_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_date', models.DateField()),
                ('forecast_date', models.DateField()),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='procurement.paymententry')),
            ],
            options={
                'ordering': ['payment_entry', 'phase_number'],
                'unique_together': {('payment_entry', 'phase_number')},
            },
        ),
    ]
