# Generated by Django 6.0.3 on 2026-04-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_paymententry_paymentphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='cost_code',
            field=models.CharField(choices=[('Material', 'Material'), ('Machining', 'Machining'), ('Coating', 'Coating'), ('Consumables', 'Consumables'), ('Subcontracts', 'Subcontracts'), ('Labour', 'Labour'), ('Freight&Customs', 'Freight&Customs'), ('Prelims', 'Prelims'), ('FOH', 'FOH'), ('Commitments', 'Commitments'), ('Contingency', 'Contingency')], max_length=50),
        ),
    ]
