# Generated by Django 6.0.3 on 2026-04-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_purchaseorder_cost_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='recovery_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='release_retention',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='paymentphase',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentphase',
            name='invoice_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentphase',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='PaymentDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('item_description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='procurement.paymententry')),
            ],
            options={
                'ordering': ['payment_entry', 'line_number'],
                'unique_together': {('payment_entry', 'line_number')},
            },
        ),
    ]
