# Generated by Django 6.0.3 on 2026-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_paymententry_recovery_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='supplier_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('company', 'po_number')},
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('company', 'supplier_name')},
        ),
    ]
