# Generated by Django 6.0.3 on 2026-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_purchaseorder_company_vendor_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_type',
            field=models.CharField(choices=[('project', 'Project'), ('asset', 'Asset'), ('inventory', 'Inventory')], db_index=True, default='project', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='project_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
