# Generated by Django 6.0.3 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_inventoryissuance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentphase',
            name='gl_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashvoucheritem',
            name='account_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='GlPeriodClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved')], db_index=True, default='submitted', max_length=20)),
                ('submitted_by', models.CharField(blank=True, default='', max_length=150)),
                ('approved_by', models.CharField(blank=True, default='', max_length=150)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-id'],
                'unique_together': {('company', 'month', 'year')},
            },
        ),
    ]
