# Generated by Django 6.0.3 on 2026-04-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delivery_number', models.CharField(max_length=255)),
                ('delivery_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_entries', to='master_data.projectitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cutting', models.IntegerField(default=0)),
                ('grooving', models.IntegerField(default=0)),
                ('bending', models.IntegerField(default=0)),
                ('fabrication', models.IntegerField(default=0)),
                ('welding', models.IntegerField(default=0)),
                ('finishing', models.IntegerField(default=0)),
                ('coating', models.IntegerField(default=0)),
                ('assembly', models.IntegerField(default=0)),
                ('installation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_entries', to='master_data.projectitem')),
            ],
        ),
    ]
