# Generated by Django 6.0.3 on 2026-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='projectdetail',
            unique_together={('company', 'project_number')},
        ),
    ]
