# Generated by Django 6.0.3 on 2026-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_projectdetail_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='revision_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='tender_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
