# Generated by Django 6.0.3 on 2026-04-17 12:26

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models


def backfill_project_item_boq_sn(apps, schema_editor):
    ProjectDetail = apps.get_model('production', 'ProjectDetail')
    ProjectItem = apps.get_model('production', 'ProjectItem')
    BoqItem = apps.get_model('estimation', 'BoqItem')

    for project in ProjectDetail.objects.all():
        boq_queryset = BoqItem.objects.filter(
            company=project.company,
            tender_number=project.tender_number,
        )

        if project.revision_number:
            boq_queryset = boq_queryset.filter(revision_number=project.revision_number)

        boq_groups = defaultdict(list)

        for boq_item in boq_queryset.order_by('description', 'sn', 'id'):
            boq_groups[(boq_item.description or '').strip()].append(boq_item)

        project_item_groups = defaultdict(list)

        for project_item in ProjectItem.objects.filter(project=project).order_by('id'):
            project_item_groups[(project_item.item_name or '').strip()].append(project_item)

        for item_name, project_items in project_item_groups.items():
            matching_boq_items = boq_groups.get(item_name, [])

            for index, project_item in enumerate(project_items):
                if project_item.boq_sn or not matching_boq_items:
                    continue

                boq_item = matching_boq_items[min(index, len(matching_boq_items) - 1)]
                project_item.boq_sn = boq_item.sn or ''
                project_item.save(update_fields=['boq_sn'])


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0011_contractrevenue_variation_budget_coating_and_more'),
        ('production', '0003_projectdetail_revision_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAllocationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('employee_id', models.CharField(db_index=True, max_length=100)),
                ('employee_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'employee_id', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectitem',
            name='boq_sn',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='TimeAllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(db_index=True, max_length=100)),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('boq_sn', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('item_name', models.CharField(db_index=True, max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.timeallocationentry')),
            ],
            options={
                'ordering': ['entry', 'project_number', 'boq_sn', 'item_name', 'id'],
            },
        ),
        migrations.RunPython(backfill_project_item_boq_sn, migrations.RunPython.noop),
    ]
