# Generated by Django on 2026-04-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0003_alter_purchaseorder_cost_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, default='', max_length=50)),
                ('tender_number', models.CharField(db_index=True, max_length=100)),
                ('clients_boq', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('freight_custom_duty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tender_number', 'sn', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MasterListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_master_items', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['item_description'],
            },
        ),
        migrations.CreateModel(
            name='TenderCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boq_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='estimation.boqitem')),
            ],
            options={
                'ordering': ['boq_item__tender_number', 'boq_item__sn'],
            },
        ),
        migrations.CreateModel(
            name='LabourCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('production_labour', 'Production Labour'), ('installation_labour', 'Installation Labour')], max_length=30)),
                ('stage', models.CharField(choices=[('Cutting', 'Cutting'), ('Grooving', 'Grooving'), ('Bending', 'Bending'), ('Fabrication', 'Fabrication'), ('Welding', 'Welding'), ('Finishing', 'Finishing'), ('Coating', 'Coating'), ('Assembly', 'Assembly'), ('Installation', 'Installation'), ('Packing', 'Packing')], max_length=30)),
                ('role', models.CharField(choices=[('skilled', 'Skilled'), ('semiSkilled', 'Semiskilled'), ('helper', 'Helper')], max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_lines', to='estimation.tendercosting')),
            ],
            options={
                'ordering': ['costing', 'category', 'stage', 'role'],
                'unique_together': {('costing', 'category', 'stage', 'role')},
            },
        ),
        migrations.CreateModel(
            name='EstimateCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('material', 'Material'), ('machining', 'Machining'), ('coating', 'Coating'), ('consumable', 'Consumable'), ('subcontract', 'Subcontract')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_lines', to='estimation.tendercosting')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='estimation.masterlistitem')),
            ],
            options={
                'ordering': ['costing', 'category'],
                'unique_together': {('costing', 'category')},
            },
        ),
    ]
