# Generated by Codex on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_labourcostline_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='prelims_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='foh_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='commitments_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='contingencies_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
