# Generated by Django 6.0.3 on 2026-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_clientdata_tenderlog_boqitem_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderlog',
            name='project_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenderlog',
            name='quote_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenderlog',
            name='status',
            field=models.CharField(choices=[('Submitted & Awaiting', 'Submitted & Awaiting'), ('Awarded to ARM', 'Awarded to ARM'), ('Awarded to Others', 'Awarded to Others'), ('Changed to VO', 'Changed to VO'), ('Cancelled', 'Cancelled'), ('Regretted', 'Regretted'), ('To Revise & Re-submit', 'To Revise & Re-submit'), ('Under Pricing', 'Under Pricing')], default='Under Pricing', max_length=100),
        ),
    ]
