# Generated by Django 6.0.3 on 2026-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_boqitem_revision_date_tenderlog_project_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderlog',
            name='tender_name',
        ),
        migrations.AddField(
            model_name='tenderlog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenderlog',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderlog',
            name='revision_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenderlog',
            name='selling_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
