# Generated by Django 6.0.3 on 2026-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0006_remove_tenderlog_tender_name_tenderlog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdata',
            name='supplier_trn_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
