# Generated by Django 6.0.3 on 2026-04-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0007_clientdata_supplier_trn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('sn', models.PositiveIntegerField(default=1)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('submitted_advance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('submitted_recovery_advance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('gross_submitted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('submitted_retention', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('submitted_release_retention', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_submitted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('submitted_vat', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_submitted_inc_vat', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('approved_advance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('approved_recovery_advance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('gross_approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('approved_retention', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('approved_release_retention', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('approved_vat', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_approved_inc_vat', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('forecast_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_number', 'sn', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('budget_material', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_machining', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_coating', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_consumables', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_subcontracts', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_production_labour', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_freight_custom', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_installation_labour', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_prelims', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_foh', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_commitments', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('budget_contingencies', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractVariationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=255)),
                ('rfv_number', models.CharField(blank=True, default='', max_length=100)),
                ('client_variation_number', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('document_ref', models.CharField(blank=True, default='', max_length=100)),
                ('submitted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('arm_letter_ref', models.CharField(blank=True, default='', max_length=100)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('client_letter_ref', models.CharField(blank=True, default='', max_length=100)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Agreed', 'Agreed'), ('Submitted', 'Submitted'), ('To be Submitted', 'To be Submitted'), ('Rejected', 'Rejected'), ('Disputed', 'Disputed'), ('Cancelled', 'Cancelled')], default='To be Submitted', max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_number', 'client_variation_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractRevenueVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='estimation.contractrevenue')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
