# Generated by Django 6.0.3 on 2026-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0008_contractpaymentlog_contractrevenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpaymentlog',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
