# Generated by Django 6.0.3 on 2026-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0009_contractpaymentlog_approved_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimatecostline',
            options={'ordering': ['costing', 'category', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='estimatecostline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AddField(
            model_name='contractpaymentlog',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AddField(
            model_name='contractvariationlog',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AddField(
            model_name='masterlistitem',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AddField(
            model_name='tenderlog',
            name='company',
            field=models.CharField(choices=[('AKR', 'AKR'), ('ARM', 'ARM')], db_index=True, default='AKR', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenderlog',
            name='tender_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='clientdata',
            unique_together={('company', 'client_name')},
        ),
        migrations.AlterUniqueTogether(
            name='tenderlog',
            unique_together={('company', 'tender_number')},
        ),
    ]
