# Generated by Django 6.0.3 on 2026-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0010_alter_estimatecostline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_coating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_commitments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_consumables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_contingencies',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_foh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_freight_custom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_installation_labour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_machining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_prelims',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_production_labour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenue',
            name='variation_budget_subcontracts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
