# Generated by Django 6.0.3 on 2026-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0020_clientdata_customer_id_po_box'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costingrevisionsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='boqitem',
            name='variation_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='costingrevisionsnapshot',
            name='variation_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='estimatecostline',
            name='rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='tendercosting',
            name='pro_rata_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='costingrevisionsnapshot',
            unique_together={('company', 'tender_number', 'revision_number', 'variation_number')},
        ),
    ]
