# Generated by Django 6.0.3 on 2026-04-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0021_alter_costingrevisionsnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='coating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='commitments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='consumables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='contingencies',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='foh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='freight_custom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='installation_labour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='machining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='prelims',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='production_labour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='contractrevenuevariation',
            name='subcontracts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
