# Generated by Django 6.0.3 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0022_contractrevenuevariation_coating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrevenue',
            name='agreed_variation_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
